### ISSUE TITLE
Enable flash

### ISSUE THREAD

**Issue by allanwolski** [facundomedica/fast_qr_reader_view#10]
Good job, I was looking for this.

Is there a way to enable flash?

**Comment by victoraugustolls** [comment]
I tried using a package for controlling the flash outside:

https://github.com/clovisnicolas/flutter_lamp

The problem is, it reserves the camera, so the preview won't open. So is there anyway to enable flash in this package? @facundomedica

**Comment by allanwolski** [comment]
I also tried using this package without success.

**Comment by facundomedica** [comment]
In order of priorities I would like to change Firebase MLKit for something else first, but I'm open to PRs.

**Comment by allanwolski** [comment]
I like Firebase MLKit and I need it for other things, like scanning the QR-Code from an image.

**Comment by victoraugustolls** [comment]
Same here, and it is really fast compared to other alternatives that I have tried. So if removing firebase causes a decrease in speed, it might not be worth it.

**Comment by josenicolas0105** [comment]
@facundomedica estimado existe una forma de usar el flash de la camara ??... quedo atento a sus comentarios.

**Comment by adlanarifzr** [comment]
I've submitted PR for this issue.

**Comment by douglaswender** [comment]
how to use toggle flash?

**Comment by douglaswender** [comment]
I need it

**Comment by douglaswender** [comment]
I did, I was using the dependencies in the pub version

**Comment by kaifigirdhar** [comment]
@douglaswender Can you please elaborate how you resolve this

**Comment by douglaswender** [comment]
I used dependencies for git. then I realized that he has a new method that is `toogleFlash()`, I just created a method to change the application state with the icon on and off.

Dependencies:
```
fast_qr_reader_view:
    git:
      url: git://github.com/facundomedica/fast_qr_reader_view.git
```
Method:

```
Future _turnFlash() async {
    controller.toggleFlash();
    controller.startScanning();
    setState(() {
      isOn = !isOn;
    });
  }
```

**Comment by kaifigirdhar** [comment]
I am getting this error: [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: MissingPluginException(No implementation found for method toggleFlash on channel fast_qr_reader_view)

**Comment by douglaswender** [comment]
Did you add the dependencies to `pubspec.yalm`? If not added add, if added use the `flutter pub get `command.

**Comment by facundomedica** [comment]
Fixed!

**Comment by douglaswender** [comment]
Thanks, are you doing null safety update? I'll probably need in next project ☺️

**Comment by facundomedica** [comment]
@douglaswender I think it's already in. I'm not a 100% sure, but seems like it. I work as a backend engineer, so it's been a while since I used Flutter 😅
