### ISSUE TITLE
Half green screen

### ISSUE THREAD

**Issue by allanwolski** [facundomedica/fast_qr_reader_view#12]
After running flutter upgrade, the half of the screen turned green.

This occurs on the beta and master channel.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel dev, v0.10.2, on Microsoft Windows [versão 10.0.17134.345], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

• No issues found!

![screenshot_20181107-212618](https://user-images.githubusercontent.com/11680596/48168024-f075db80-e2d4-11e8-9bf7-1b7806b3234d.jpg)

**Comment by facundomedica** [comment]
Hi! Can you check if this library does the same: https://github.com/flutter/plugins/tree/master/packages/camera ? Also, does this happens only in a single device or in multiple?

**Comment by allanwolski** [comment]
The problem does not happen with the camera plugin.
At the moment I have only Samsung Galaxy S5 to test.

Do you have any idea what might be causing this?
Initially this started happening only on the master channel, but now it happens in dev and soon will arrive in the beta.

**Comment by allanwolski** [comment]
@facundomedica, did you check this problem?

**Comment by facundomedica** [comment]
Not really, I hadn't been able to replicate it. Can you try with the latest Flutter version?

**Comment by allanwolski** [comment]
Same problem with the latest version.
I really need this to publish my app.

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.11.10-pre.2, on Microsoft Windows [versão 10.0.17134.407], locale pt-BR)
[√] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[√] Android Studio (version 3.2)
[√] Connected device (1 available)

![screenshot_20181121-233952](https://user-images.githubusercontent.com/11680596/48876803-4c695580-ede7-11e8-9c36-138d6b86e71b.jpg)

**Comment by allanwolski** [comment]
Problem solved with Flutter 1.0

https://github.com/flutter/flutter/issues/24289
https://github.com/flutter/flutter/issues/24402
