### ISSUE TITLE
[Feature request] Read QR codes from storage.

### ISSUE THREAD

**Issue by modulovalue** [facundomedica/fast_qr_reader_view#16]
I'm looking for a way to scan QR codes that are present in the gallery. This is a feature no QR scanning library offers and it's really essential for some applications like cryptocurrency wallets. 

Do you know if this could be done with the underlying iOS & Android libraries?

Thanks!

**Comment by Sheharyar566** [comment]
Can someone please tell me why this issue was closed?

**Comment by modulovalue** [comment]
@Sheharyar566 Because we did not need this feature anymore. You should probably open a new issue.
