### ISSUE TITLE
Take picture from the camera

### ISSUE THREAD

**Issue by c0h1b4** [facundomedica/fast_qr_reader_view#19]
Hello,

I am developing an App that needs to read a QR Code and then take a picture of an object after reading the qr code. 
When I added the official camera dependency, there was a lot of compiler issues of duplicated symbols in the compiler. 
Is there a way to use the fast_qr_reader to also capture the photo?

Thanks,
David

**Comment by c0h1b4** [comment]
From the flutter team:

@c0h1b4
I've checked the issue, that's because developers define same class FLTCam in CameraPlugin.m(from plugin camera) and FastQrReaderViewPlugin.h(from fast_qr_reader_view).
I do think this is the responsibility of plugin developers to avoid this, like add customized prefix for their class and methods, etc. Otherwise, the developer who want to use them both will have to do this.
Closing #26548

So please, rename the class on the plugin.

**Comment by c0h1b4** [comment]
Pull request https://github.com/facundomedica/fast_qr_reader_view/pull/20

**Comment by facundomedica** [comment]
Closed as #20 was merged
