### ISSUE TITLE
How can I use fast_qr_reader_view with firebase_ml_vision

### ISSUE THREAD

**Issue by potikorn** [facundomedica/fast_qr_reader_view#21]
Hello,
I have a problem when using this plugin along with firebase_ml_vision.
How can I resolve this?

**Comment by potikorn** [comment]
I tried to used this solution its work,
But I was wondering any better solution for this problem?

```
fast_qr_reader_view:
    git:
      url: git://github.com/martflu/fast_qr_reader_view.git
```

**Comment by facundomedica** [comment]
That means that the package isn't updated in the pub. I'll update the package in a couple of days so you can stop using the git URL. But currently I recommend using the git URL directly.
