### ISSUE TITLE
Error building APK on Android

### ISSUE THREAD

**Issue by IrosTheBeggar** [facundomedica/fast_qr_reader_view#26]
I got this error on Android after installing this plugin

```
         *********************************************************
WARNING: This version of path_provider will break your Android build if it or its dependencies aren't compatible with AndroidX.
         See https://goo.gl/CP92wY for more information on the problem and how to fix it.
         This warning prints for all Android build failures. The real root cause of the error may be unrelated.
         *********************************************************

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:preReleaseBuild'.
> Android dependency 'android.arch.lifecycle:runtime' has different version for the compile (1.0.0) and runtime (1.1.0) classpath. You should manually set the same version via DependencyResolution

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 0s
```

**Comment by pneves001** [comment]
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/VisionProcessorBase.java:18: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;                              
                                 ^                                      
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/barcodescanning/BarcodeScanningProcessor.java:16: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;                              
                                 ^                                      
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java:25: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;                             
                                 ^                                      
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java:26: error: package android.support.annotation does not exist
import android.support.annotation.RequiresPermission;                   
                                 ^                                      
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java:18: error: package android.support.annotation does not exist
import android.support.annotation.NonNull;                              
                                 ^                                      
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java:19: error: package android.support.annotation does not exist
import android.support.annotation.Nullable;                             
                                 ^                                      
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/VisionProcessorBase.java:133: error: cannot find symbol
            @NonNull T results,                                         
             ^                                                          
  symbol:   class NonNull                                               
  location: class VisionProcessorBase<T>                                
  where T is a type-variable:                                           
    T extends Object declared in class VisionProcessorBase              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/VisionProcessorBase.java:134: error: cannot find symbol
            @NonNull FrameMetadata frameMetadata);//,                   
             ^                                                          
  symbol:   class NonNull                                               
  location: class VisionProcessorBase<T>                                
  where T is a type-variable:                                           
    T extends Object declared in class VisionProcessorBase              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/VisionProcessorBase.java:137: error: cannot find symbol
    protected abstract void onFailure(@NonNull Exception e);            
                                       ^                                
  symbol:   class NonNull                                               
  location: class VisionProcessorBase<T>                                
  where T is a type-variable:                                           
    T extends Object declared in class VisionProcessorBase              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/barcodescanning/BarcodeScanningProcessor.java:78: error: cannot find symbol
            @NonNull List<FirebaseVisionBarcode> barcodes,              
             ^                                                          
  symbol:   class NonNull                                               
  location: class BarcodeScanningProcessor                              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/barcodescanning/BarcodeScanningProcessor.java:79: error: cannot find symbol
            @NonNull FrameMetadata frameMetadata) { //,                 
             ^                                                          
  symbol:   class NonNull                                               
  location: class BarcodeScanningProcessor                              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/barcodescanning/BarcodeScanningProcessor.java:93: error: cannot find symbol
    protected void onFailure(@NonNull Exception e) {                    
                              ^                                         
  symbol:   class NonNull                                               
  location: class BarcodeScanningProcessor                              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java:159: error: cannot find symbol
  @RequiresPermission(Manifest.permission.CAMERA)                       
   ^                                                                    
  symbol:   class RequiresPermission                                    
  location: class CameraSource                                          
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java:186: error: cannot find symbol
  @RequiresPermission(Manifest.permission.CAMERA)                       
   ^                                                                    
  symbol:   class RequiresPermission                                    
  location: class CameraSource                                          
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java:402: error: cannot find symbol
        @Nullable Camera.Size pictureSize) {                            
         ^                                                              
  symbol:   class Nullable                                              
  location: class SizePair                                              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java:413: error: cannot find symbol
    @Nullable                                                           
     ^                                                                  
  symbol:   class Nullable                                              
  location: class SizePair                                              
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java:263: error: cannot find symbol
    void startScanning(@NonNull Result result) {                        
                        ^                                               
  symbol:   class NonNull                                               
  location: class FastQrReaderViewPlugin                                
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java:329: error: cannot find symbol
    void stopScanning(@NonNull Result result) {                         
                       ^                                                
  symbol:   class NonNull                                               
  location: class FastQrReaderViewPlugin                                
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java:392: error: cannot find symbol
        QrReader(final String cameraName, final String resolutionPreset, final ArrayList<String> formats, @NonNull final Result result) {
                                                                                                           ^
  symbol:   class NonNull                                               
  location: class FastQrReaderViewPlugin.QrReader                       
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/FastQrReaderViewPlugin.java:563: error: cannot find symbol
        private void open(@Nullable final Result result) {              
                           ^                                            
  symbol:   class Nullable                                              
  location: class FastQrReaderViewPlugin.QrReader                       
/Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/java/VisionProcessorBase.java:116: error: cannot find symbol
                            public void onFailure(@NonNull Exception e) {
                                                   ^                    
  symbol: class NonNull                                                 
Note: /Users/philipneves/flutter/.pub-cache/hosted/pub.dartlang.org/fast_qr_reader_view-0.1.5/android/src/main/java/co/apperto/fastqrreaderview/common/CameraSource.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.                    
21 errors                                                               
                                                                        
FAILURE: Build failed with an exception.                                
                                                                        
* What went wrong:                                                      
Execution failed for task ':fast_qr_reader_view:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.        
                                                                        
* Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
                                                                        
* Get more help at https://help.gradle.org

**Comment by pneves001** [comment]
This is due to androidX not being supported by the plugin.

**Comment by James-A-White** [comment]
Have you fully upgraded your project to AndroidX?  This is the error I was getting before migrating my project to AndroidX.  If you remove the dependency to fast_qr_reader_view, does the problem go away?

I finally got it working in my environment following [these steps](https://github.com/facundomedica/fast_qr_reader_view/issues/32#issuecomment-471146441).

Good luck!
