### ISSUE TITLE
Format of scanned code

### ISSUE THREAD

**Issue by darrendube** [facundomedica/fast_qr_reader_view#27]
When barcode is scanned, may you please also return the code format scanned.

**Comment by facundomedica** [comment]
Hey, thanks for opening the issue, this has been in the roadmap since the beginning but I haven't had the time to implement it yet. You can start working on it and send a PR if you want. Thanks!

**Comment by facundomedica** [comment]
I forgot that I opened this same issue myself: https://github.com/facundomedica/fast_qr_reader_view/issues/2
