### ISSUE TITLE
Qr code does not scan on Android

### ISSUE THREAD

**Issue by Sadoge** [facundomedica/fast_qr_reader_view#29]
When trying to scan a qr code, the function onCodeRead does not return any value on Android version 6.0.1 (api level 23). Since the minimum is 21 I would expect it to work fine on this one. The qr code scanning works fine on version above.

**Comment by James-A-White** [comment]
It's working fine for me... try the steps in [this post ](https://github.com/facundomedica/fast_qr_reader_view/issues/32#issuecomment-471146441)and see if they help.

**Comment by Sadoge** [comment]
I think it had to do with internet connection since the next day it worked fine but forgot to close the issue. I am sorry!
