### ISSUE TITLE
Error building APK in release mode

### ISSUE THREAD

**Issue by allanwolski** [facundomedica/fast_qr_reader_view#30]
Execution failed for task ':fast_qr_reader_view:verifyReleaseResources'.
> java.util.concurrent.ExecutionException: com.android.builder.internal.aapt.v2.Aapt2Exception: Android resource linking failed
  \build\fast_qr_reader_view\intermediates\res\merged\release\values\values.xml:276: error: resource android:attr/fontVariationSettings not found.
  \build\fast_qr_reader_view\intermediates\res\merged\release\values\values.xml:277: error: resource android:attr/ttcIndex not found.
  error: failed linking references.

**Comment by thomasgarrison** [comment]
I'm having this issue too

**Comment by facundomedica** [comment]
Have you tried using the library from the git repo instead of the pub?

**Comment by allanwolski** [comment]
The problem exists only in release mode with the git repository.

**Comment by thomasgarrison** [comment]
Same. I'm using the git repository and AndroidX

**Comment by thomasgarrison** [comment]
Got this fixed by changing the compileSdkVersion in the plugin's build.gradle from verison 27 to 28

**Comment by allanwolski** [comment]
I fixed this by creating a new Flutter project and moving my files.
