### ISSUE TITLE
Empty Licensing

### ISSUE THREAD

**Issue by kcin9** [facundomedica/fast_qr_reader_view#31]
The project license is now empty. Would you consider adding one into it? @facundomedica 

Thanks.

**Comment by facundomedica** [comment]
@kcin9 an MIT license would be good to you?

**Comment by kcin9** [comment]
Definitely! Thanks man.

**Comment by jcn2185** [comment]
@facundomedica hey - love the library. Did you ever officially change the license to MIT?

**Comment by facundomedica** [comment]
Added MIT license
