### ISSUE TITLE
Barcode scanning on Android 8.1.0 go not working

### ISSUE THREAD

**Issue by MarcelEdward** [facundomedica/fast_qr_reader_view#46]
On a real device with the android 8.1.0 go version we get an error, it seems that on this version the barcode lib is not installed.

How to fix this error ?

E/BarcodeNativeHandle( 7792): Error Loading module
E/BarcodeNativeHandle( 7792): com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source:8)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.vision.zzm.zzq(Unknown Source:28)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.vision.zzm.isOperational(Unknown Source:9)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.vision.barcode.BarcodeDetector.isOperational(Unknown Source:23)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.firebase_ml.zzoj.zza(Unknown Source:23)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.firebase_ml.zzoj.zza(Unknown Source:42)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.firebase_ml.zznd.call(Unknown Source:4)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.firebase_ml.zzmy.zza(Unknown Source:29)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.firebase_ml.zzmz.run(Unknown Source:2)
E/BarcodeNativeHandle( 7792): 	at android.os.Handler.handleCallback(Handler.java:790)
E/BarcodeNativeHandle( 7792): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/BarcodeNativeHandle( 7792): 	at com.google.android.gms.internal.firebase_ml.zze.dispatchMessage(Unknown Source:6)
E/BarcodeNativeHandle( 7792): 	at android.os.Looper.loop(Looper.java:164)
E/BarcodeNativeHandle( 7792): 	at android.os.HandlerThread.run(HandlerThread.java:65)
E/BarcodeScanProc( 7792): Barcode detection failed com.google.firebase.ml.common.FirebaseMLException: Waiting for the barcode detection model to be downloaded. Please wait.
I/Camera  ( 7792): handleMessage: 16
W/DynamiteModule( 7792): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule( 7792): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
W/DynamiteModule( 7792): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
I/DynamiteModule( 7792): Considering local module com.google.android.gms.vision.dynamite:0 and remote module com.google.android.gms.vision.dynamite:0
I/Camera  ( 7792): handleMessage: 16

**Comment by bas24** [comment]
The same here 
Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.

**Comment by tokonu** [comment]
Had the same issue,
Updating the dependencies and adding `com.google.firebase:firebase-ml-vision-barcode-model` fixed the issue

```
dependencies {
        api 'androidx.appcompat:appcompat:1.1.0'
        api 'androidx.annotation:annotation:1.1.0'
        api 'com.google.firebase:firebase-core:17.2.1'
        api 'com.google.firebase:firebase-ml-vision:24.0.0'
        api 'com.google.firebase:firebase-ml-vision-barcode-model:16.0.1'
    }
```

https://github.com/tokonu/fast_qr_reader_view/blob/9b8b727b74462cdaf1dad903256c03c49f28f2b1/android/build.gradle#L35

**Comment by facundomedica** [comment]
Not using Firebase anymore. Fixed!
