### ISSUE TITLE
exception was thrown: NoSuchMethodError

### ISSUE THREAD

**Issue by bachbonglong** [facundomedica/fast_qr_reader_view#47]
I have error "**Another exception was thrown: NoSuchMethodError: The method '[]' was called on null.**" . Help me

![image](https://user-images.githubusercontent.com/42697834/60232825-ef2b0a80-98c7-11e9-9966-052fa677f7cf.png)

**Comment by hisan-web** [comment]
mee to

**Comment by facundomedica** [comment]
This should be fixed!
