### ISSUE TITLE
overrides a deprecated API

### ISSUE THREAD

**Issue by pishguy** [facundomedica/fast_qr_reader_view#50]
Note: C:\Users\mahdi\AppData\Roaming\Pub\Cache\hosted\pub.dartlang.org\fast_qr_reader_view-0.1.5\android\src\main\java\co\apperto\fastqrreaderview\common\CameraSource.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.

**Comment by chrystoffer** [comment]
Any solution?

**Comment by MarcelEdward** [comment]
Is there gonna be an update for this package ?

**Comment by facundomedica** [comment]
Deprecated APIs are warnings, they shouldn't affect the app's functionality. I just published a refactor anyway 😄
