### ISSUE TITLE
requested by various other libraries at [[16.5.0,16.5.0]]

### ISSUE THREAD

**Issue by pishguy** [facundomedica/fast_qr_reader_view#54]
how can i resolve this problem:

> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Could not determine the dependencies of task ':fast_qr_reader_view:compileDebugAidl'.
> > The library com.google.android.gms:play-services-measurement-base is being requested by various other libraries at [[16.5.0,16.5.0]], but resolves to 16.3.0. Disable the plugin and check your dependencies tree using ./gradlew :app:dependencies.
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 9s
> Finished with error: Gradle task assembleDebug failed with exit code 1

        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath 'com.google.gms:google-services:4.0.2'

**app/build.gradle:**

apply plugin: 'com.google.gms.google-services'

**Comment by facundomedica** [comment]
A refactor was just published 👌
