### ISSUE TITLE
The following RangeError was thrown attaching to the render tree

### ISSUE THREAD

**Issue by alsdns016** [facundomedica/fast_qr_reader_view#55]
When I run the simulator, I get the following error.

I do not get an error when I run my phone (apk, ipa).

![스크린샷 2019-07-19 오전 10 25 50](https://user-images.githubusercontent.com/18530105/61502617-9c002f80-aa0f-11e9-9463-1b3a3a7dc14d.png)

![스크린샷 2019-07-19 오전 10 23 05](https://user-images.githubusercontent.com/18530105/61502598-82f77e80-aa0f-11e9-8ea9-b08ce7145bc1.png)

**Comment by facundomedica** [comment]
That's probably because the simulator doesn't have a camera
