### ISSUE TITLE
[Feature request] return image when QR code is read

### ISSUE THREAD

**Issue by cfransen** [facundomedica/fast_qr_reader_view#56]
I would like to store the image in which the QR code was recognized.  I'm looking for suggestions about how to participate properly in getting such an enhancement approved and implemented.  I'm willing to work on it.

**Comment by cfransen** [comment]
Looking at other's comments, I see I can simply take a photo when the QR code is recognized.  Will pursue that.

**Comment by ShiroYacha** [comment]
How did it work? I am trying to do the same but it was a mess as i have to dispose the controller and initialize the camera controller and still somehow the image is very very dimed. Did you make it work?

**Comment by giraffe-team** [comment]
I did not pursue this to implementation.  Knowing the presumed solution, I went on to other things.  I still hope to store the image with the QR code in it and will either figure out how to get all the controllers aligned or perhaps dust off my Objective C or whatever and dig into the component.  Sorry I can't be of more help at this point.
