### ISSUE TITLE
Unable to initialise controller

### ISSUE THREAD

**Issue by joemarbrillo** [facundomedica/fast_qr_reader_view#63]
When I am running this piece of code:
controller = new QRReaderController(
        cameras[0], ResolutionPreset.high, codeFormats, (dynamic value) {
      print(value); // the result!
      // ... do something
      // wait 3 seconds then start scanning again.
      new Future.delayed(const Duration(seconds: 3), controller.startScanning);
    });
    controller.initialize().then((_) {
      if (!mounted) {
        return;
      }
      setState(() {});
      controller.startScanning();
    });

The following error occurred:
W/DynamiteModule(22722): Local module descriptor class for com.google.android.gms.vision.dynamite.barcode not found.
I/DynamiteModule(22722): Considering local module com.google.android.gms.vision.dynamite.barcode:0 and remote module com.google.android.gms.vision.dynamite.barcode:0
D/BarcodeNativeHandle(22722): Cannot load feature, fall back to load whole module.
W/DynamiteModule(22722): Local module descriptor class for com.google.android.gms.vision.dynamite not found.
E/flutter (22722): [ERROR:flutter/shell/platform/android/platform_view_android_jni.cc(39)] java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/os/ConfigurationCompat;
E/flutter (22722): 	at com.google.android.gms.internal.firebase_ml.zznv.zzlm(Unknown Source)
E/flutter (22722): 	at com.google.android.gms.internal.firebase_ml.zznv.zza(Unknown Source)
E/flutter (22722): 	at com.google.firebase.ml.vision.barcode.FirebaseVisionBarcodeDetector.<init>(Unknown Source)
E/flutter (22722): 	at com.google.firebase.ml.vision.barcode.FirebaseVisionBarcodeDetector.zza(Unknown Source)
E/flutter (22722): 	at com.google.firebase.ml.vision.FirebaseVision.getVisionBarcodeDetector(Unknown Source)
E/flutter (22722): 	at co.apperto.fastqrreaderview.java.barcodescanning.BarcodeScanningProcessor.<init>(BarcodeScanningProcessor.java:55)
E/flutter (22722): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader.open(FastQrReaderViewPlugin.java:655)
E/flutter (22722): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader.access$1400(FastQrReaderViewPlugin.java:426)
E/flutter (22722): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader$1.run(FastQrReaderViewPlugin.java:555)
E/flutter (22722): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin$QrReader.<init>(FastQrReaderViewPlugin.java:560)
E/flutter (22722): 	at co.apperto.fastqrreaderview.FastQrReaderViewPlugin.onMethodCall(FastQrReaderViewPlugin.java:269)
E/flutter (22722): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:222)
E/flutter (22722): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:96)
E/flutter (22722): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:656)
E/flutter (22722): 	at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter (22722): 	at android.os.MessageQueue.next(MessageQueue.java:323)
E/flutter (22722): 	at android.os.Looper.loop(Looper.java:141)
E/flutter (22722): 	at android.app.ActivityThread.main(ActivityThread.java:5601)
E/flutter (22722): 	at java.lang.reflect.Method.invoke(Native Method)
E/flutter (22722): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:774)
E/flutter (22722): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:652)
E/flutter (22722): Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.os.ConfigurationCompat" on path: DexPathList[[zip file "/data/app/com.emagi.barcode_scanner-1/base.apk"],nativeLibraryDirectories=[/data/app/com.emagi.barcode_scanner-1/lib/arm64, /data/app/com.emagi.barcode_scanner-1/base.apk!/lib/arm64-v8a, /vendor/lib64, /system/lib64]]
E/flutter (22722): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/flutter (22722): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/flutter (22722): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/flutter (22722): 	... 21 more
E/flutter (22722): 	Suppressed: java.lang.ClassNotFoundException: android.support.v4.os.ConfigurationCompat
E/flutter (22722): 		at java.lang.Class.classForName(Native Method)
E/flutter (22722): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/flutter (22722): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/flutter (22722): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/flutter (22722): 		... 22 more
E/flutter (22722): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
E/flutter (22722): 
F/flutter (22722): [FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
F/libc    (22722): Fatal signal 6 (SIGABRT), code -6 in tid 22722 (barcode_scanner)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'Xiaomi/land/land:6.0.1/MMB29M/V10.2.2.0.MALMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 22722, tid: 22722, name: barcode_scanner  >>> com.emagi.barcode_scanner <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni.cc(76)] Check failed: CheckException(env). 
'
    x0   0000000000000000  x1   00000000000058c2  x2   0000000000000006  x3   0000000000000000
    x4   0000000000000000  x5   0000000000000001  x6   0000000000000000  x7   0000000000000000
    x8   0000000000000083  x9   0000007f98e03a70  x10  0000000000000003  x11  0000000000000000
    x12  0000007f98e03a70  x13  00000055b511b110  x14  00000055b4bfdd50  x15  0000007f95ccc000
    x16  0000007f98dfc6a8  x17  0000007f98dbebdc  x18  0000007f9918e840  x19  0000007f99223088
    x20  0000007f99222fc8  x21  000000000000000b  x22  0000000000000006  x23  000000000000001a
    x24  0000000000000001  x25  00000055b45d9e58  x26  00000055b4f54b60  x27  00000055b4f54b48
    x28  0000007f991663fc  x29  0000007fcb779570  x30  0000007f98dbc378
    sp   0000007fcb779570  pc   0000007f98dbebe4  pstate 0000000020000000
backtrace:
    #00 pc 000000000006abe4  /system/lib64/libc.so (tgkill+8)
    #01 pc 0000000000068374  /system/lib64/libc.so (pthread_kill+68)
    #02 pc 00000000000212f8  /system/lib64/libc.so (raise+28)
    #03 pc 000000000001ba98  /system/lib64/libc.so (abort+60)
    #04 pc 00000000011d4c3c  /data/app/com.emagi.barcode_scanner-1/lib/arm64/libflutter.so (offset 0x11c0000)
    #05 pc 00000000011c6f9c  /data/app/com.emagi.barcode_scanner-1/lib/arm64/libflutter.so (offset 0x11c0000)
    #06 pc 00000000011c549c  /data/app/com.emagi.barcode_scanner-1/lib/arm64/libflutter.so (offset 0x11c0000)
    #07 pc 000000000120d9ac  /data/app/com.emagi.barcode_scanner-1/lib/arm64/libflutter.so (offset 0x11c0000)
    #08 pc 00000000011d55a8  /data/app/com.emagi.barcode_scanner-1/lib/arm64/libflutter.so (offset 0x11c0000)
    #09 pc 00000000011da7c8  /data/app/com.emagi.barcode_scanner-1/lib/arm64/libflutter.so (offset 0x11c0000)
    #10 pc 000000000001c004  /system/lib64/libutils.so (_ZN7android6Looper9pollInnerEi+524)
    #11 pc 000000000001c268  /system/lib64/libutils.so (_ZN7android6Looper8pollOnceEiPiS1_PPv+80)
    #12 pc 00000000000d6d98  /system/lib64/libandroid_runtime.so (_ZN7android18NativeMessageQueue8pollOnceEP7_JNIEnvP8_jobjecti+48)
    #13 pc 000000007429e82c  /data/dalvik-cache/arm64/system@framework@boot.oat (offset 0x2563000)
Tombstone written to: /data/tombstones/tombstone_02
Lost connection to device.

**Comment by plamenGo** [comment]
I have the same issue :(

**Comment by facundomedica** [comment]
Big refactor published, should be solved! 😄
