### ISSUE TITLE
Obtener el path de la imagen del scan

### ISSUE THREAD

**Issue by slandaeta** [facundomedica/fast_qr_reader_view#70]
Como puedo obtener la imagen que se escanea? Cuando indetifica un QR o un BARCODE, el pluggin decodifica este valor obteniendo el STRING pero es posible obtener la imagen escaneada?

**Comment by facundomedica** [comment]
Hola! No, por ahora no es posible. Habría que ver si se puede pasar de alguna manera los bytes del frame que detectó el código. La otra opción sería reconstruir el código.
