### ISSUE TITLE
Is there a way to scan qr codes from images?

### ISSUE THREAD

**Issue by Sheharyar566** [facundomedica/fast_qr_reader_view#82]
I am looking for a way to scan qr codes from images, i.e. something like when user picks an image from Library and the package decodes the QR if there's any. Does this library provide such a feature? If yes, then how can I use it?

**Comment by facundomedica** [comment]
Hello! No, it doesn't. Although it could be added if there's a brave enough dev 😄 If an image picker is capable of passing a path or something similar, it shouldn't be that hard, but I'm not sure. I know for sure how to do it on Android, but I don't have an iPhone to test the iOS plugin.
