### ISSUE TITLE
To work with ProGuard

### ISSUE THREAD

**Issue by vin89423** [facundomedica/fast_qr_reader_view#9]
I need some help on building a release APK after using this widget.

First of all, i like this widget and it did save my project.

The problem is when i build release APK with ProGuard. It show lots of errors because of my ProGuard rules is not compatible with `firebase` and `gms`.
I search hours on internet to find `firebase`, `gms` rules but still not working.
I can turn off ProGuard to skip those errors but it sound not the best way.

Could you tell me what ProGuard rules are you using to build project with `firebase` and `gms`.

Thanks a lot =)

**Comment by facundomedica** [comment]
ML Kit is now being used instead of Firebase 👌
